@startuml
left to right direction
class Группа
class Дисциплина
class "Группа-дисциплина"
class Лаба
class Лабосдача
class Студент
class Преподаватель

Студент "*" -- "*" Группа: состоит в
Преподаватель "1" -- "*" "Группа-дисциплина": преподаёт у
"Группа-дисциплина" "*" -- "*" Лаба: получает
Студент "1" -- "*" Лабосдача: сдаёт
Лабосдача "*" -- "1" Лаба: относится к
Группа "1" -- "1" "Группа-дисциплина": является частью
Дисциплина "1" -- "1" "Группа-дисциплина": является частью
@enduml
