@startuml main_classes_in_reality_class_diagram
left to right direction
together {
    class Группа
    class Дисциплина
}
class Студент
class Преподаватель

Преподаватель "1" -- "*" Группа: преподаёт у 
Преподаватель "*" -- "*" Дисциплина: преподаёт
Группа "*" -- "*" Дисциплина: изучает
Дисциплина "*" -- "*" Студент: изучается
Группа "*" -- "*" Студент: является объединением

@enduml